export const pokeNatures = {
    "hardy": ["", ""],
    "lonely": ["atk", "def"],
    "brave": ["atk", "spd"],
    "adamant": ["atk", "spatk"],
    "naughty": ["atk", "spdef"],
    "bold": ["def", "atk"],
    "docile": ["", ""],
    "relaxed": ["def", "spd"],
    "impish": ["def", "spatk"],
    "lax": ["def", "spdef"],
    "timid": ["spd", "atk"],
    "hasty": ["spd", "def"],
    "serious": ["", ""],
    "jolly": ["spd", "spatk"],
    "naive": ["spd", "spdef"],
    "modest": ["spatk", "atk"],
    "mild": ["spatk", "def"],
    "quiet": ["spatk", "spd"],
    "bashful": ["", ""],
    "rash": ["spatk", "spdef"],
    "calm": ["spdef", "atk"],
    "gentle": ["spdef", "def"],
    "sassy": ["spdef", "spd"],
    "careful": ["spdef", "spatk"],
    "quirky": ["", ""]
};

export const pokeForms = new Map([
    ["giratina", ["giratina-altered", "giratina"]],
    ["giratina-altered", ["giratina-altered", "giratina"]],
    ["giratina-origin", ["giratina-origin", "giratina"]],
    ["urshifu", ["urshifu-single-strike", "urshifu"]],
    ["urshifu-single-strike", ["urshifu-single-strike", "urshifu"]],
    ["urshifu-rapid-strike", ["urshifu-rapid-strike", "urshifu"]],
]);