export const pokeNatures = {
    "hardy": ["", ""],
    "lonely": ["atk", "def"],
    "brave": ["atk", "spd"],
    "adamant": ["atk", "spatk"],
    "naughty": ["atk", "spdef"],
    "bold": ["def", "atk"],
    "docile": ["", ""],
    "relaxed": ["def", "spd"],
    "impish": ["def", "spatk"],
    "lax": ["def", "spdef"],
    "timid": ["spd", "atk"],
    "hasty": ["spd", "def"],
    "serious": ["", ""],
    "jolly": ["spd", "spatk"],
    "naive": ["spd", "spdef"],
    "modest": ["spatk", "atk"],
    "mild": ["spatk", "def"],
    "quiet": ["spatk", "spd"],
    "bashful": ["", ""],
    "rash": ["spatk", "spdef"],
    "calm": ["spdef", "atk"],
    "gentle": ["spdef", "def"],
    "sassy": ["spdef", "spd"],
    "careful": ["spdef", "spatk"],
    "quirky": ["", ""]
};
// map for regional and special forms, also some default forms like giratina-altered, shaymin-land, darmanitan -> darmanitan-standard
export const pokeForms = new Map([
    ["raichu-alola", ["raichu-alola", "raichu", "Alolan Raichu"]],
    ["sandshrew-alola", ["sandshrew-alola", "sandshrew", "Alolan Sandshrew"]],
    ["sandslash-alola", ["sandslash-alola", "sandslash", "Alolan Sandslash"]],
    ["vulpix-alola", ["vulpix-alola", "vulpix", "Alolan Vulpix"]],
    ["ninetales-alola", ["ninetales-alola", "ninetales", "Alolan Ninetales"]],
    ["diglett-alola", ["diglett-alola", "diglett", "Alolan Diglett"]],
    ["dugtrio-alola", ["dugtrio-alola", "dugtrio", "Alolan Dugtrio"]],
    ["meowth-alola", ["meowth-alola", "meowth", "Alolan Meowth"]],
    ["meowth-galar", ["meowth-galar", "meowth", "Galarian Meowth"]],
    ["persian-alola", ["persian-alola", "persian", "Alolan Persian"]],
    ["growlithe-hisui", ["growlithe-hisui", "growlithe", "Hisuian Growlithe"]],
    ["arcanine-hisui", ["arcanine-hisui", "arcanine", "Hisuian Arcanine"]],
    ["geodude-alola", ["geodude-alola", "geodude", "Alolan Geodude"]],
    ["graveler-alola", ["graveler-alola", "graveler", "Alolan Graveler"]],
    ["golem-alola", ["golem-alola", "golem", "Alolan Golem"]],
    ["ponyta-galar", ["ponyta-galar", "ponyta", "Galarian Ponyta"]],
    ["rapidash-galar", ["rapidash-galar", "rapidash", "Galarian Rapidash"]],
    ["slowpoke-galar", ["slowpoke-galar", "slowpoke", "Galarian Slowpoke"]],
    ["slowbro-galar", ["slowbro-galar", "slowbro", "Galarian Slowbro"]],
    ["farfetchd-galar", ["farfetchd-galar", "farfetchd", "Galarian Farfetch'd"]],
    ["rattata-alola", ["rattata-alola", "rattata", "Alolan Rattata"]],
    ["raticate-alola", ["raticate-alola", "raticate", "Alolan Raticate"]],
    ["grimer-alola", ["grimer-alola", "grimer", "Alolan Grimer"]],
    ["muk-alola", ["muk-alola", "muk", "Alolan Muk"]],
    ["voltorb-hisui", ["voltorb-hisui", "voltorb", "Hisuian Voltorb"]],
    ["electrode-hisui", ["electrode-hisui", "electrode", "Hisuian Electrode"]],
    ["exeggutor-alola", ["exeggutor-alola", "exeggutor", "Alolan Exeggutor"]],
    ["marowak-alola", ["marowak-alola", "marowak", "Alolan Marowak"]],
    ["wheezing-galar", ["wheezing-galar", "wheezing", "Galarian Wheezing"]],
    ["mr-mime", ["mr-mime", "mr-mime", "Mr. Mime"]],
    ["mr-mime-galar", ["mr-mime-galar", "mr-mime", "Galarian Mr. Mime"]],
    ["tauros-paldea", ["tauros-paldea-combat-breed", "tauros", "Paldean Tauros (Combat Breed)"]],
    ["tauros-paldea-combat-breed", ["tauros-paldea-combat-breed", "tauros", "Paldean (Tauros Combat Breed)"]],
    ["tauros-paldea-blaze-breed", ["tauros-paldea-blaze-breed", "tauros", "Paldean Tauros (Blaze Breed)"]],
    ["tauros-paldea-aqua-breed", ["tauros-paldea-aqua-breed", "tauros", "Paldean Tauros (Aqua Breed)"]],
    ["articuno-galar", ["articuno-galar", "articuno", "Galarian Articuno"]],
    ["zapdos-galar", ["zapdos-galar", "zapdos", "Galarian Zapdos"]],
    ["moltres-galar", ["moltres-galar", "moltres", "Galarian Moltres"]],
    ["castform-sunny", ["castform-sunny", "castform", "Castform (Sunny)"]],
    ["castform-rainy", ["castform-rainy", "castform", "Castform (Rainy)"]],
    ["castform-snowy", ["castform-snowy", "castform", "Castform (Snowy)"]],
    ["rotom-heat", ["rotom-heat", "rotom", "Rotom (Heat)"]],
    ["rotom-wash", ["rotom-wash", "rotom", "Rotom (Wash)"]],
    ["rotom-frost", ["rotom-frost", "rotom", "Rotom (Frost)"]],
    ["rotom-fan", ["rotom-fan", "rotom", "Rotom (Fan)"]],
    ["rotom-mow", ["rotom-mow", "rotom", "Rotom (Mow)"]],
    ["deoxys", ["deoxys-normal", "deoxys", "Deoxys"]],
    ["deoxys-normal", ["deoxys-normal", "deoxys", "Deoxys"]],
    ["deoxys-attack", ["deoxys-attack", "deoxys", "Deoxys (Attack Forme)"]],
    ["deoxys-defense", ["deoxys-defense", "deoxys", "Deoxys (Defense Forme)"]],
    ["deoxys-speed", ["deoxys-speed", "deoxys", "(Deoxys Speed Forme)"]],
    ["dialga-origin", ["dialga-origin", "dialga", "Dialga (Origin Forme)"]],
    ["palkia-origin", ["palkia-origin", "palkia", "Palkia (Origin Forme)"]],
    ["giratina", ["giratina-altered", "giratina", "Giratina"]],
    ["giratina-altered", ["giratina-altered", "giratina", "Giratina"]],
    ["giratina-origin", ["giratina-origin", "giratina", "Giratina (Origin Forme)"]],
    ["shaymin", ["shaymin-land", "shaymin", "Shaymin (Land Forme)"]],
    ["shaymin-land", ["shaymin-land", "shaymin", "Shaymin (Land Forme)"]],
    ["shaymin-sky", ["shaymin-sky", "shaymin", "Shaymin (Sky Forme)"]],
    ["basculin", ["basculin-red-striped", "basculin", "Basculin (Red Striped Form)"]],
    ["basculin-red-striped", ["basculin-red-striped", "basculin", "Basculin (Red Striped Form)"]],
    ["basculin-blue-striped", ["basculin-blue-striped", "basculin", "Basculin (Blue Striped Form)"]],
    ["basculin-white-striped", ["basculin-white-striped", "basculin", "Basculin (White Striped Form)"]],
    ["darmanitan", ["darmanitan-standard", "darmanitan", "Darmanitan"]],
    ["darmanitan-standard", ["darmanitan-standard", "darmanitan", "Darmanitan"]],
    ["darmanitan-zen", ["darmanitan-zen", "darmanitan", "Darmanitan (Zen Mode)"]],
    ["darumaka-galar", ["darumaka-galar", "darumaka", "Galarian Darumaka"]],
    ["darmanitan-galar", ["darmanitan-galar-standard", "darmanitan", "Galarian Darmanitan"]],
    ["darmanitan-galar-standard", ["darmanitan-galar-standard", "darmanitan", "Galarian Darmanitan"]],
    ["darmanitan-galar-zen", ["darmanitan-galar-zen", "darmanitan", "Galarian Darmanitan (Zen Mode)"]],
    ["tornadus", ["tornadus-incarnate", "tornadus", "Tornadus (Incarnate)"]],
    ["tornadus-incarnate", ["tornadus-incarnate", "tornadus", "Tornadus (Incarnate)"]],
    ["tornadus-therian", ["tornadus-therian", "tornadus", "Tornadus (Therian)"]],
    ["thundurus", ["thundurus-incarnate", "thundurus", "Thundurus (Incarnate)"]],
    ["thundurus-incarnate", ["thundurus-incarnate", "thundurus", "Thundurus (Incarnate)"]],
    ["thundurus-therian", ["thundurus-therian", "thundurus", "Thundurus (Therian)"]],
    ["landorus", ["landorus-incarnate", "landorus", "Landorus (Incarnate)"]],
    ["landorus-incarnate", ["landorus-incarnate", "landorus", "Landorus (Incarnate)"]],
    ["landorus-therian", ["landorus-therian", "landorus", "Landorus (Therian)"]],
    ["kyurem-white", ["kyurem-white", "kyurem", "Kyurem (White)"]],
    ["kyurem-black", ["kyurem-black", "kyurem", "Kyurem (Black)"]],
    ["keldeo", ["keldeo-ordinary", "keldeo", "Keldeo (Ordinary)"]],
    ["keldeo-ordinary", ["keldeo-ordinary", "keldeo", "Keldeo (Ordinary)"]],
    ["keldeo-resolute", ["keldeo-resolute", "keldeo", "Keldeo (Resolute)"]],
    ["meloetta", ["meloetta-aria", "meloetta", "Meloetta (Aria)"]],
    ["meloetta-aria", ["meloetta-aria", "meloetta", "Meloetta (Aria)"]],
    ["meloetta-pirouette", ["meloetta-pirouette", "meloetta", "Meloetta (Pirouette)"]],
    ["aegislash", ["aegislash-shield", "aegislash", "Aegislash (Shield)"]],
    ["aegislash-shield", ["aegislash-shield", "aegislash", "Aegislash (Shield)"]],
    ["aegislash-blade", ["aegislash-blade", "aegislash", "Aegislash (Blade)"]],
    ["zygarde-10", ["zygarde-10", "zygarde", "Zygarde (10% Forme)"]],
    ["zygarde", ["zygarde-50", "zygarde", "Zygarde (50% Forme)"]],
    ["zygarde-50", ["zygarde-50", "zygarde", "Zygarde (50% Forme)"]],
    ["zygarde-complete", ["zygarde-complete", "zygarde", "Zygarde (Complete Forme)"]],
    ["hoopa-unbound", ["hoopa-unbound", "hoopa", "Hoopa (Unbound)"]],
    ["oricorio", ["oricorio-baile", "oricorio", "Oricorio (Baile Style)"]],
    ["oricorio-baile", ["oricorio-baile", "oricorio", "Oricorio (Baile Style)"]],
    ["oricorio-pom-pom", ["oricorio-pom-pom", "oricorio", "Oricorio (Pom-Pom Style)"]],
    ["oricorio-pau", ["oricorio-pau", "oricorio", "Oricorio (Pa'u Style)"]],
    ["oricorio-sensu", ["oricorio-sensu", "oricorio", "Oricorio (Sensu Style)"]],
    ["lycanroc", ["lycanroc-midday", "lycanroc", "Lycanroc (Midday Form)"]],
    ["lycanroc-midday", ["lycanroc-midday", "lycanroc", "Lycanroc (Midday Form)"]],
    ["lycanroc-midnight", ["lycanroc-midnight", "lycanroc", "Lycanroc (Midnight Form)"]],
    ["lycanroc-dusk", ["lycanroc-dusk", "lycanroc", "Lycanroc (Dusk Form)"]],
    ["wishiwashi", ["wishiwashi-solo", "wishiwashi", "Wishiwashi (Solo Form)"]],
    ["wishiwashi-solo", ["wishiwashi-solo", "wishiwashi", "Wishiwashi (Solo Form)"]],
    ["wishiwashi-school", ["wishiwashi-school", "wishiwashi", "Wishiwashi (School Form)"]],
    ["minior", ["minior-red-meteor", "minior", "Minior (Meteor Form)"]],
    ["minior-red-meteor", ["minior-red-meteor", "minior", "Minior (Meteor Form)"]],
    ["minior-red", ["minior-red", "minior", "Minior (Core Form)"]],
    ["mimikyu", ["mimikyu-disguised", "mimikyu", "Mimikyu (Disguised Form)"]],
    ["mimikyu-disguised", ["mimikyu-disguised", "mimikyu", "Mimikyu (Disguised Form)"]],
    ["mimikyu-busted", ["mimikyu-busted", "mimikyu", "Mimikyu (Busted Form)"]],
    ["necrozma-dusk", ["necrozma-dusk", "necrozma", "Necrozma (Dusk Mane)"]],
    ["necrozma-dawn", ["necrozma-dawn", "necrozma", "Necrozma (Dawn Wings)"]],
    ["cramorant-gulping", ["cramorant-gulping", "cramorant", "Cramorant (Gulping Form)"]],
    ["cramorant-gorging", ["cramorant-gorging", "cramorant", "Cramorant (Gorging Form)"]],
    ["toxtricity", ["toxtricity-amped", "toxtricity", "Toxtricity (Amped Form)"]],
    ["toxtricity-amped", ["toxtricity-amped", "toxtricity", "Toxtricity (Amped Form)"]],
    ["toxtricity-low-key", ["toxtricity-low-key", "toxtricity", "Toxtricity (Low Key Form)"]],
    ["eiscue", ["eiscue-ice", "eiscue", "Eiscue (Ice Face)"]],
    ["eiscue-ice", ["eiscue-ice", "eiscue", "Eiscue (Ice Face)"]],
    ["eiscue-noice", ["eiscue-noice", "eiscue", "Eiscue (Noice Face)"]],
    ["indeedee", ["indeedee-male", "indeedee", "Indeedee (Male)"]],
    ["indeedee-male", ["indeedee-male", "indeedee", "Indeedee (Male)"]],
    ["indeedee-female", ["indeedee-female", "indeedee", "Indeedee (Female)"]],
    ["morpeko", ["morpeko-full-belly", "morpeko", "Morpeko (Full Belly Mode)"]],
    ["morpeko-full-belly", ["morpeko-full-belly", "morpeko", "Morpeko (Full Belly Mode)"]],
    ["morpeko-hangry", ["morpeko-hangry", "morpeko", "Morpeko (Hangry Mode)"]],
    ["urshifu", ["urshifu-single-strike", "urshifu", "(Urshifu Single Strike Style)"]],
    ["urshifu-single-strike", ["urshifu-single-strike", "urshifu", "Urshifu (Single Strike Style)"]],
    ["urshifu-rapid-strike", ["urshifu-rapid-strike", "urshifu", "Urshifu (Rapid Strike Style)"]],
    ["calyrex-ice", ["calyrex-ice", "calyrex", "Calyrex (Ice Rider)"]],
    ["calyrex-shadow", ["calyrex-shadow", "calyrex", "Calyrex (Shadow Rider)"]],
    ["enamorus", ["enamorus-incarnate", "enamorus", "Enamorus (Incarnate)"]],
    ["enamorus-incarnate", ["enamorus-incarnate", "enamorus", "Enamorus (Incarnate Forme)"]],
    ["enamorus-therian", ["enamorus-therian", "enamorus", "Enamorus (Therian Forme)"]],
    ["oinkologne", ["oinkologne", "oinkologne", "Oinkologne (Male)"]],
    ["oinkologne-male", ["oinkologne", "oinkologne", "Oinkologne (Male)"]],
    ["oinkologne-female", ["oinkologne-female", "oinkologne", "Oinkologne (Female)"]],
    ["maushold", ["maushold", "maushold", "Maushold (Family of Three)"]],
    ["maushold-family-of-three", ["maushold-family-of-three", "maushold", "Maushold (Family of Three)"]],
    ["maushold-family-of-four", ["maushold-family-of-four", "maushold", "Maushold (Family of Four)"]],
    ["palafin", ["palafin", "palafin", "Palafin (Zero Form)"]],
    ["palafin-hero", ["palafin-hero", "palafin", "Palafin (Hero Form)"]],
    ["tatsugiri", ["tatsugiri", "tatsugiri", "Tatsugiri (Curly Form)"]],
    ["tatsugiri-curly", ["tatsugiri", "tatsugiri", "Tatsugiri (Curly Form)"]],
    ["tatsugiri-stretchy", ["tatsugiri-stretchy", "tatsugiri", "Tatsugiri (Stretchy Form)"]],
    ["tatsugiri-droopy", ["tatsugiri-droopy", "tatsugiri", "Tatsugiri (Droopy Form)"]],
    ["dudunsparce", ["dudunsparce", "dudunsparce", "Dudunsparce (Two-Segment Form)"]],
    ["dudunsparce-two-segment", ["dudunsparce", "dudunsparce", "Dudunsparce (Two-Segment Form)"]],
    ["dudunsparce-three-segment", ["dudunsparce-three-segment", "dudunsparce", "Dudunsparce (Three-Segment Form)"]],
    ["gimmighoul", ["gimmighoul", "gimmighoul", "Gimmighoul (Chest Form)"]],
    ["gimmighoul-chest", ["gimmighoul", "gimmighoul", "Gimmighoul (Chest Form)"]],
    ["gimmighoul-roaming", ["gimmighoul-roaming", "gimmighoul", "Gimmighoul (Roaming Form)"]],
    ["ogerpon", ["ogerpon", "ogerpon", "Ogerpon (Teal Mask)"]],
    ["ogerpon-wellspring-mask", ["ogerpon-wellspring-mask", "ogerpon", "Ogerpon (Wellspring Mask)"]],
    ["ogerpon-hearthflame-mask", ["ogerpon-hearthflame-mask", "ogerpon", "Ogerpon (Hearthflame Mask)"]],
    ["ogerpon-cornerstone", ["ogerpon-cornerstone", "ogerpon", "Ogerpon (Cornerstone Mask)"]],
    ["typhlosion-hisui", ["typhlosion-hisui", "typhlosion", "Hisuian Typhlosion"]],
    ["wooper-paldea", ["wooper-paldea", "wooper", "Paldean Wooper"]],
    ["slowking-galar", ["slowking-galar", "slowking", "Galarian Slowking"]],
    ["qwilfish-hisui", ["qwilfish-hisui", "qwilfish", "Hisuian Qwilfish"]],
    ["sneasel-hisui", ["sneasel-hisui", "sneasel", "Hisuian Sneasel"]],
    ["corsola-galar", ["corsola-galar", "corsola", "Galarian Corsola"]],
    ["zigzagoon-galar", ["zigzagoon-galar", "zigzagoon", "Galarian Zigzagoon"]],
    ["linoone-galar", ["linoone-galar", "linoone", "Galarian Linoone"]],
    ["samurott-hisui", ["samurott-hisui", "samurott", "Hisuian Samurott"]],
    ["lilligant-hisui", ["lilligant-hisui", "lilligant", "Hisuian Lilligant"]],
    ["yamask-galar", ["yamask-galar", "yamask", "Galarian Yamask"]],
    ["zorua-hisui", ["zorua-hisui", "zorua", "Hisuian Zorua"]],
    ["zoroark-hisui", ["zoroark-hisui", "zoroark", "Hisuian Zoroark"]],
    ["stunfisk-galar", ["stunfisk-galar", "stunfisk", "Galarian Stunfisk"]],
    ["braviary-hisui", ["braviary-hisui", "braviary", "Hisuian Braviary"]],
    ["sliggoo-hisui", ["sliggoo-hisui", "sliggoo", "Hisuian Sliggoo"]],
    ["goodra-hisui", ["goodra-hisui", "goodra", "Hisuian Goodra"]],
    ["avalugg-hisui", ["avalugg-hisui", "avalugg", "Hisuian Avalugg"]],
    ["decidueye-hisui", ["decidueye-hisui", "decidueye", "Hisuian Decidueye"]],
    ["wormadam", ["wormadam-plant", "wormadam", "Wormadam (Plant Cloak)"]],
    ["wormadam-plant", ["wormadam-plant", "wormadam", "Wormadam (Plant Cloak)"]],
    ["wormadam-sandy", ["wormadam-sandy", "wormadam", "Wormadam (Sandy Cloak)"]],
    ["wormadam-trash", ["wormadam-trash", "wormadam", "Wormadam (Trash Cloak)"]],
    ["meowstic", ["meowstic-male", "meowstic", "Mewostic (Male)"]],
    ["meowstic-male", ["meowstic-male", "meowstic", "Mewostic (Male)"]],
    ["meowstic-female", ["meowstic-female", "meowstic", "Mewostic (Female)"]],
    ["pumpkaboo", ["pumpkaboo-average", "pumpkaboo", "Pumpkaboo (Average Size)"]],
    ["pumpkaboo-average", ["pumpkaboo-average", "pumpkaboo", "Pumpkaboo (Average Size)"]],
    ["gourgeist", ["gourgeist-average", "gourgeist", "Gourgesti (Average Size)"]],
    ["gourgeist-average", ["gourgeist-average", "gourgeist", "Gourgesti (Average Size)"]],
    ["basculegion", ["basculegion-male", "basculegion", "Basculegion (Male)"]],
    ["basculegion-male", ["basculegion-male", "basculegion", "Basculegion (Male)"]],
    ["basculegion-female", ["basculegion-female", "basculegion", "Basculegion (Female)"]],
]);

// forms missing or not supported: deerling, sawsbuck, burmy, shellos/gastrodon, genesect, vivillon, flabebe, florges, furfrou, xerneas modes, alcremie